version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nextstrap
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - default
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextstrap
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  default:
volumes:
  postgres-data:
